Added enviroment variable for Mock factory to simulate gpio and enabled thruster control testing on launch

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -8,50 +8,52 @@ on:
       - docker-adjustments
   workflow_dispatch:
 
-jobs:
-  build:
-    runs-on: ubuntu-24.04  # Use Ubuntu 24.04 (Noble Numbat) for ROS 2 Jazzy Jalisco
+    jobs:
+      build:
+        runs-on: ubuntu-24.04  # Use Ubuntu 24.04 (Noble Numbat) for ROS 2 Jazzy Jalisco
     steps:
       # Check out the repository
       - name: Checkout code
         uses: actions/checkout@v4
-      
-      # Set up ROS 2 (jazzy)
+
+        # Set up ROS 2 (jazzy)
       - name: Set up ROS 2
         uses: ros-tooling/setup-ros@v0.7 # gets version from repo
         with:
           required-ros-distributions: jazzy # updated to use Jazzy, also matches the dockerfile now
-      
-      # Install dependencies from requirements.txt
+
+          # Install dependencies from requirements.txt
       - name: Install dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y python3-pip
           pip install crccheck gpiozero
-      
-      # Rest of your steps remain the same
+
+          # Rest of your steps remain the same
       - name: Build
         run: |
           chmod +x scripts/build.sh
           scripts/build.sh
-      
+
       - name: Run
+        env:
+          GPIOZERO_PIN_FACTORY: MockFactory 
         run: |
           chmod +x scripts/run.sh
           scripts/run.sh
-      
+
       - name: Verify nodes # updated to use jazzy
         run: |
           source /opt/ros/jazzy/setup.bash 
           EXPECTED_NODES="/rov/ROV_main /rov/thrust_control /rov/thrust_to_spi"
           NODE_LIST=$(ros2 node list)
           for NODE in $EXPECTED_NODES; do
-            if [[ ! "$NODE_LIST" =~ "$NODE" ]]; then
-              echo "ERROR: $NODE node not found"
-              exit 1
-            fi
-          done
-          echo "All nodes successfully launched."
-      
+          if [[ ! "$NODE_LIST" =~ "$NODE" ]]; then
+        echo "ERROR: $NODE node not found"
+        exit 1
+        fi
+        done
+        echo "All nodes successfully launched."
+
       - name: Success
         run: echo "Success!"
