updated github action testing to check for active nodes

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -46,6 +46,19 @@ jobs:
           chmod +x scripts/run.sh
           scripts/run.sh
 
+      # Verify active nodes
+      - name: Verify nodes
+        run: |
+          EXPECTED_NODES="/rov/ROV_main /rov/thrust_control /rov/thrust_to_spi"
+          NODE_LIST=$(ros2 node list)
+          for NODE in $EXPECTED_NODES; do
+            if [[ ! "$NODE_LIST" =~ "$NODE" ]]; then
+              echo "ERROR: $NODE node not found"
+              exit 1
+            fi
+          done
+          echo "All nodes successfully launched."
+
       # Success message
       - name: Success
         run: echo "Success!"
